import Foundation
import Shared

public struct PeeriSettings: Codable, Equatable {
    // MARK: - General Settings
    public var downloadDirectory: String
    public var logLevel: String

    // MARK: - Connection Settings
    public var maxConcurrentDownloads: Int
    public var maxConnectionPerServer: Int
    public var split: Int
    public var minSplitSize: String

    // MARK: - Speed Limits
    public var maxOverallDownloadLimit: Int  // KB/s, 0 = unlimited
    public var maxOverallUploadLimit: Int    // KB/s, 0 = unlimited

    // MARK: - BitTorrent Settings
    public var btEnableLPD: Bool
    public var btMaxPeers: Int
    public var btRequestPeerSpeedLimit: String
    public var enablePeerExchange: Bool

    // MARK: - Advanced Settings
    public var checkIntegrity: Bool
    public var continueDownloads: Bool

    public init(
        downloadDirectory: String = NSHomeDirectory() + "/Downloads",
        logLevel: String = "info",
        maxConcurrentDownloads: Int = 5,
        maxConnectionPerServer: Int = 10,
        split: Int = 10,
        minSplitSize: String = "1M",
        maxOverallDownloadLimit: Int = 0,
        maxOverallUploadLimit: Int = 50,
        btEnableLPD: Bool = true,
        btMaxPeers: Int = 50,
        btRequestPeerSpeedLimit: String = "100K",
        enablePeerExchange: Bool = true,
        checkIntegrity: Bool = true,
        continueDownloads: Bool = true
    ) {
        self.downloadDirectory = downloadDirectory
        self.logLevel = logLevel
        self.maxConcurrentDownloads = maxConcurrentDownloads
        self.maxConnectionPerServer = maxConnectionPerServer
        self.split = split
        self.minSplitSize = minSplitSize
        self.maxOverallDownloadLimit = maxOverallDownloadLimit
        self.maxOverallUploadLimit = maxOverallUploadLimit
        self.btEnableLPD = btEnableLPD
        self.btMaxPeers = btMaxPeers
        self.btRequestPeerSpeedLimit = btRequestPeerSpeedLimit
        self.enablePeerExchange = enablePeerExchange
        self.checkIntegrity = checkIntegrity
        self.continueDownloads = continueDownloads
    }

    public static let `default` = PeeriSettings()

    /// Generate aria2.conf file content from settings
    public func toAria2ConfigString(logPath: String) -> String {
        """
        # Aria2 Configuration - Generated by Peeri

        # Downloads directory
        dir=\(downloadDirectory)

        # Enable JSON-RPC server
        enable-rpc=true
        rpc-listen-all=true
        rpc-listen-port=16800
        rpc-secret=peeri

        # BitTorrent settings
        bt-enable-lpd=\(btEnableLPD ? "true" : "false")
        bt-max-peers=\(btMaxPeers)
        bt-request-peer-speed-limit=\(btRequestPeerSpeedLimit)
        enable-peer-exchange=\(enablePeerExchange ? "true" : "false")

        # Connection settings
        max-concurrent-downloads=\(maxConcurrentDownloads)
        max-connection-per-server=\(maxConnectionPerServer)
        max-overall-download-limit=\(maxOverallDownloadLimit > 0 ? "\(maxOverallDownloadLimit)K" : "0")
        max-overall-upload-limit=\(maxOverallUploadLimit > 0 ? "\(maxOverallUploadLimit)K" : "0")
        min-split-size=\(minSplitSize)
        split=\(split)

        # Logging
        log=\(logPath)
        log-level=\(logLevel)

        # Other settings
        check-integrity=\(checkIntegrity ? "true" : "false")
        continue=\(continueDownloads ? "true" : "false")
        """
    }

    /// Generate runtime-changeable options for aria2
    public func toAria2GlobalOptions() -> [String: String] {
        [
            "max-concurrent-downloads": "\(maxConcurrentDownloads)",
            "max-connection-per-server": "\(maxConnectionPerServer)",
            "split": "\(split)",
            "min-split-size": minSplitSize,
            "max-overall-download-limit": maxOverallDownloadLimit > 0 ? "\(maxOverallDownloadLimit)K" : "0",
            "max-overall-upload-limit": maxOverallUploadLimit > 0 ? "\(maxOverallUploadLimit)K" : "0",
            "bt-max-peers": "\(btMaxPeers)",
            "bt-request-peer-speed-limit": btRequestPeerSpeedLimit,
            "log-level": logLevel
        ]
    }
}

// MARK: - SharedKey Extension

extension SharedKey where Self == FileStorageKey<PeeriSettings>.Default {
    public static var settings: Self {
        Self[.fileStorage(
            FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
                .appendingPathComponent("Peeri/settings.json")
        ), default: .default]
    }
}
